"""
Export translations to formatted PDF
"""

from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from datetime import datetime
from pathlib import Path


class PDFExporter:
    """Export translations to PDF format"""
    
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        """Setup custom PDF styles"""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1e40af'),
            spaceAfter=30,
            alignment=TA_CENTER
        ))
        
        self.styles.add(ParagraphStyle(
            name='OriginalText',
            parent=self.styles['Normal'],
            fontSize=11,
            leading=16,
            textColor=colors.HexColor('#374151'),
            spaceAfter=12
        ))
        
        self.styles.add(ParagraphStyle(
            name='TranslatedText',
            parent=self.styles['Normal'],
            fontSize=11,
            leading=16,
            textColor=colors.HexColor('#059669'),
            spaceAfter=12
        ))
    
    async def create_translation_pdf(
        self,
        original_text: str,
        translated_text: str,
        output_path: str,
        source_language: str,
        title: str = "Translation",
        include_original: bool = True,
        layout: str = 'side-by-side'
    ):
        """
        Create formatted PDF with translation
        
        Args:
            original_text: Original text
            translated_text: Translated text
            output_path: Output PDF path
            source_language: Source language code
            title: Document title
            include_original: Include original text
            layout: 'side-by-side' or 'sequential'
        """
        try:
            # Create PDF document
            doc = SimpleDocTemplate(
                output_path,
                pagesize=A4,
                rightMargin=72,
                leftMargin=72,
                topMargin=72,
                bottomMargin=18
            )
            
            # Build content
            story = []
            
            # Title
            story.append(Paragraph(title, self.styles['CustomTitle']))
            story.append(Spacer(1, 12))
            
            # Metadata
            lang_names = {'ne': 'Nepali', 'si': 'Sinhalese', 'en': 'English'}
            metadata = f"Translated from {lang_names.get(source_language, source_language)} to English | {datetime.now().strftime('%B %d, %Y')}"
            story.append(Paragraph(metadata, self.styles['Normal']))
            story.append(Spacer(1, 20))
            
            if layout == 'side-by-side' and include_original:
                # Side-by-side layout
                story.append(self._create_side_by_side_table(original_text, translated_text))
            else:
                # Sequential layout
                if include_original:
                    story.append(Paragraph("<b>Original Text:</b>", self.styles['Heading2']))
                    story.append(Spacer(1, 12))
                    story.append(Paragraph(original_text, self.styles['OriginalText']))
                    story.append(Spacer(1, 20))
                
                story.append(Paragraph("<b>Translated Text:</b>", self.styles['Heading2']))
                story.append(Spacer(1, 12))
                story.append(Paragraph(translated_text, self.styles['TranslatedText']))
            
            # Footer
            story.append(Spacer(1, 30))
            story.append(Paragraph(
                "<i>Generated by LitLingua - AI-Powered Translation Platform</i>",
                self.styles['Normal']
            ))
            
            # Build PDF
            doc.build(story)
            
        except Exception as e:
            raise Exception(f"PDF export failed: {str(e)}")
    
    def _create_side_by_side_table(self, original: str, translated: str):
        """Create side-by-side comparison table"""
        data = [
            [Paragraph("<b>Original</b>", self.styles['Heading3']),
             Paragraph("<b>Translation</b>", self.styles['Heading3'])],
            [Paragraph(original, self.styles['OriginalText']),
             Paragraph(translated, self.styles['TranslatedText'])]
        ]
        
        table = Table(data, colWidths=[3.5*inch, 3.5*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#e5e7eb')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#1f2937')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#d1d5db')),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f9fafb')])
        ]))
        
        return table
